[project]
name = "ncdac-opi-analytics"
version = "0.1.0"
description = "This dbt project models data from the North Carolina Department of Adult Correction."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-duckdb>=1.9.6",
    "duckdb>=1.4.1",
]
